{% set name = "code-server" %}
{% set version = "3.0.2" %}
{% set base_version = version.split("-")[0] %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/cdr/{{ name }}/archive/{{ base_version }}.tar.gz
  sha256: 37c580906da3f432f58040b9f5e0f13f800516102a34e2da0e3ecc5e15e4e046
  patches:
    - node-binary.patch

build:
  number: 0
  binary_relocation: false  # [osx]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python 2.7.*
    - nodejs 12.*
    - yarn
    - pkg-config  # [linux]
    - ripgrep
  host:
    - nbin 1.2.7.*
    - libxkbfile  # [linux]
    - libsecret  # [linux]
    - xorg-libx11  # [linux]
  run:
    - vs2015_runtime  # [win]
    - icu  # [not win]
    - libsecret  # [linux]
    - libuv  # [not win]
    - libxkbfile  # [linux]
    - openssl >=1.1.1d  # [not win]
    - xorg-libx11  # [linux]
    - zlib  # [not win]
  run_constrained:   # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  commands:
    - code-server --help

about:
  home: https://github.com/cdr/code-server
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE.vscode.txt
    - ThirdPartyNotices.vscode.txt
  summary: Run VS Code on a remote server.

extra:
  recipe-maintainers:
    - xhochy
