{% set name = "code-server" %}
{% set version = "4.98.0" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/coder/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: c7d5e389be56e54d300ef60610a4c877fe54cf62f0df4bb6fc2e3f04618009eb  # [linux64]
  url: https://github.com/coder/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: e60578f9c628a2296a20e9e4d4142559e850ac934bb7e7985425c095557a9212  # [aarch64]
  url: https://github.com/coder/code-server/releases/download/v{{ version }}/code-server-{{ version }}-macos-arm64.tar.gz  # [osx and arm64]
  sha256: 44936cd0ec095e275e3effd8a0808c503ca298362d1eb172c748d754b64c2909  # [osx and arm64]
  folder: code-server

build:
  number: 0
  binary_relocation: false
  skip: true  # [win or (osx and x86_64)]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - nodejs 18.*
  run:
    - nodejs 18.*

test:
  commands:
    - code-server --help
    - $CONDA_PREFIX/share/code-server/lib/vscode/node_modules/@vscode/ripgrep/bin/rg --version

about:
  home: https://github.com/cdr/code-server
  license: MIT
  license_family: MIT
  license_file:
    - code-server/LICENSE
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
