{% set name = "code-server" %}
{% set version = "4.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: 1e6a74d24e9dd56e8db79ed169c388edb10b082b7bd56d0221e006a51899851a  # [linux64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: 5be518813e1cd00021fd1b26aa6f7be2e9e47b64bff8d48b14f93f3661a739ba  # [aarch64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-macos-amd64.tar.gz  # [osx]
  sha256: 1459c425c1faf4cc1b2830264778adc0e31c98dc07f2d6ca230ffa1524b442ef  # [osx]
  folder: code-server

build:
  number: 0
  binary_relocation: false  # [osx]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - nodejs 16.*
  run:
    - nodejs 16.*

test:
  commands:
    - code-server --help

about:
  home: https://github.com/cdr/code-server
  license: MIT
  license_family: MIT
  license_file:
    - code-server/LICENSE
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
