{% set name = "code-server" %}
{% set version = "4.99.2" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/coder/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: 528701df7df747ea77711c1c48e69642fb8234b36920a6412433f93691210542  # [linux64]
  url: https://github.com/coder/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: 63cda9e18893e1b73fb944e97e4b3d89de749d4335a38f8bfddf2052f10a4da3  # [aarch64]
  url: https://github.com/coder/code-server/releases/download/v{{ version }}/code-server-{{ version }}-macos-arm64.tar.gz  # [osx and arm64]
  sha256: 4128a09fea929a509f094b0b8d44bd5613c60a193bf2b13bf0f89f377d68c2e1  # [osx and arm64]
  folder: code-server

build:
  number: 0
  binary_relocation: false
  skip: true  # [win or (osx and x86_64)]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - nodejs 20.*
  run:
    - nodejs 20.*

test:
  commands:
    - code-server --help
    - $CONDA_PREFIX/share/code-server/lib/vscode/node_modules/@vscode/ripgrep/bin/rg --version

about:
  home: https://github.com/cdr/code-server
  license: MIT
  license_family: MIT
  license_file:
    - code-server/LICENSE
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
