{% set name = "code-server" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - url: https://github.com/cdr/{{ name }}/archive/{{ version }}.tar.gz
    sha256: d1eb04fae806be4a07bf7fb5cf2fe3ce4925a8fe4d7193017f5d6963c14dcd45
    patches:
      - no-local-webkit.patch
  - url: https://github.com/microsoft/vscode/archive/1.43.2.tar.gz
    sha256: 3dc8a809c711db89db7549d8be12e3b803e841fbcd6aa516b7a6afd09549d5e7
    folder: lib/vscode

build:
  number: 0
  binary_relocation: False  # [osx]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python 2.7.*
    - nodejs 12.*
    - yarn
  host:
    - libxkbfile  # [linux]
    - libsecret  # [linux]
    - xorg-libx11  # [linux]
  run:
    - nodejs >=10,<13
    - libxkbfile  # [linux]
    - libsecret  # [linux]
    - xorg-libx11  # [linux]
  run_constrained:  # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  commands:
    - code-server --help

about:
  home: https://github.com/cdr/code-server
  license: MIT
  license_family: MIT
  license_file:
   - LICENSE.txt
   - lib/vscode/LICENSE.txt
   - lib/vscode/ThirdPartyNotices.txt
  summary: 'Run VS Code on a remote server.'

extra:
  recipe-maintainers:
    - xhochy
