{% set name = "code-server" %}
{% set version = "4.93.1" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: 8c001f865cf082e914375e8f28e9e15b25faa1f3de455ddc30158d54fc2326d3  # [linux64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: 1e29278529d0d8376d1344ed816b37f4e88a5ba16ce74cb1173fe437c8519852  # [aarch64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-macos-amd64.tar.gz  # [osx]
  sha256: 149f128d3ad18377ffee92f658887f70487557258965224e05e9700489cc3d31  # [osx]
  folder: code-server

build:
  number: 0
  binary_relocation: false
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ stdlib("c") }}
  host:
    - nodejs 18.*
  run:
    - nodejs 18.*

test:
  commands:
    - code-server --help
    - $CONDA_PREFIX/share/code-server/lib/vscode/node_modules/@vscode/ripgrep/bin/rg --version

about:
  home: https://github.com/cdr/code-server
  license: MIT
  license_family: MIT
  license_file:
    - code-server/LICENSE
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
