{% set name = "code-server" %}
{% set version = "4.99.4" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/coder/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: ff15590177d4d42bba7eec950e7820e47ad724d883c1d2310736158a28056600  # [linux64]
  url: https://github.com/coder/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: eeec4138a9cb66306c879b960a590b48a3b4b9a0fb60af6b99c241ad9b57aec8  # [aarch64]
  url: https://github.com/coder/code-server/releases/download/v{{ version }}/code-server-{{ version }}-macos-arm64.tar.gz  # [osx and arm64]
  sha256: 66ef9563e3695ae4be9d4137e80b5e24d79828f15105233176cb605871a615c1  # [osx and arm64]
  folder: code-server

build:
  number: 0
  binary_relocation: false
  skip: true  # [win or (osx and x86_64)]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - nodejs 20.*
  run:
    - nodejs 20.*

test:
  commands:
    - code-server --help
    - $CONDA_PREFIX/share/code-server/lib/vscode/node_modules/@vscode/ripgrep/bin/rg --version

about:
  home: https://github.com/cdr/code-server
  license: MIT
  license_family: MIT
  license_file:
    - code-server/LICENSE
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
