{% set name = "code-server" %}
{% set version = "4.96.4" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/coder/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: b3f9025d00f2cdf61caf83945ef7225d4a3eb576c4c007e45868f45713e39c8e  # [linux64]
  url: https://github.com/coder/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: 8471a70ac790ce43c302c43451e45eb2cf000a927db5bb2c8a9899b72e32fff6  # [aarch64]
  url: https://github.com/coder/code-server/releases/download/v{{ version }}/code-server-{{ version }}-macos-arm64.tar.gz  # [osx and arm64]
  sha256: beb7e92590bf3c7dc60baf1e5f15ffba2694bb10049d24871361c04a63404e5b  # [osx and arm64]
  folder: code-server

build:
  number: 0
  binary_relocation: false
  skip: true  # [win or (osx and x86_64)]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - nodejs 18.*
  run:
    - nodejs 18.*

test:
  commands:
    - code-server --help
    - $CONDA_PREFIX/share/code-server/lib/vscode/node_modules/@vscode/ripgrep/bin/rg --version

about:
  home: https://github.com/cdr/code-server
  license: MIT
  license_family: MIT
  license_file:
    - code-server/LICENSE
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
