schema_version: 1

context:
  name: code-server
  version: "4.141.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://github.com/coder/code-server/releases/download/v${{ version }}/code-server-${{ version }}-linux-amd64.tar.gz
      sha256: 65bcd20b524d03eb1b5adb7f360244599ef0e5b74089a46a982d32c074b97a29
      target_directory: code-server
  - if: linux and aarch64
    then:
      url: https://github.com/coder/code-server/releases/download/v${{ version }}/code-server-${{ version }}-linux-arm64.tar.gz
      sha256: e5cc78da1d631c6cf6162f9b18eeaa8ee9d3239e1a88bb99d0602cdc5fa1852d
      target_directory: code-server
  - if: osx and arm64
    then:
      url: https://github.com/coder/code-server/releases/download/v${{ version }}/code-server-${{ version }}-macos-arm64.tar.gz
      sha256: ab45ad960725bdcdfb92998ef54feb2f479079224315ce44a4f49c54093453c9
      target_directory: code-server

build:
  skip:
    - win
    - osx and x86_64
  number: 0
  dynamic_linking:
    binary_relocation: false

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
  host:
    - nodejs 22.*
  run:
    - nodejs 22.*

tests:
  - script:
      - code-server --help

about:
  license: MIT
  license_file:
    - code-server/LICENSE
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.
  homepage: https://coder.com
  repository: https://github.com/cdr/code-server
  documentation: https://coder.com/docs/code-server

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
