schema_version: 1

context:
  name: code-server
  version: "4.108.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://github.com/coder/code-server/releases/download/v${{ version }}/code-server-${{ version }}-linux-amd64.tar.gz
      sha256: eefeebffb275eb64463a3e03937815a1cd551cc2f765865b12a06e70e24ab5cf
      target_directory: code-server
  - if: linux and aarch64
    then:
      url: https://github.com/coder/code-server/releases/download/v${{ version }}/code-server-${{ version }}-linux-arm64.tar.gz
      sha256: 0e441373e3e1dd5af907677eab9759844f8685cf2533801c3e367282f71f16ff
      target_directory: code-server
  - if: osx and arm64
    then:
      url: https://github.com/coder/code-server/releases/download/v${{ version }}/code-server-${{ version }}-macos-arm64.tar.gz
      sha256: 40883620e607fa0585153a6b08857ef12dba1f99d668ce8c9190c1770d706c6b
      target_directory: code-server

build:
  skip:
    - win
    - osx and x86_64
  number: 0
  dynamic_linking:
    binary_relocation: false

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
  host:
    - nodejs 22.*
  run:
    - nodejs 22.*

tests:
  - script:
      - code-server --help
      - $CONDA_PREFIX/share/code-server/lib/vscode/node_modules/@vscode/ripgrep/bin/rg --version

about:
  license: MIT
  license_file:
    - code-server/LICENSE
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.
  homepage: https://coder.com
  repository: https://github.com/cdr/code-server
  documentation: https://coder.com/docs/code-server

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
