schema_version: 1

context:
  name: code-server
  version: "4.109.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://github.com/coder/code-server/releases/download/v${{ version }}/code-server-${{ version }}-linux-amd64.tar.gz
      sha256: 15ca7472e4522f214e01143673559938536571d7152c5fca3cb42966e79a688b
      target_directory: code-server
  - if: linux and aarch64
    then:
      url: https://github.com/coder/code-server/releases/download/v${{ version }}/code-server-${{ version }}-linux-arm64.tar.gz
      sha256: 56af7eb5d85135482844798c607cca6be315f27a41e3b4ed83152442c7646bdc
      target_directory: code-server
  - if: osx and arm64
    then:
      url: https://github.com/coder/code-server/releases/download/v${{ version }}/code-server-${{ version }}-macos-arm64.tar.gz
      sha256: 5e3f81eb2d6d2086bfc878cb8b7c9fe68839a024df924dbc5395ddab851ade79
      target_directory: code-server

build:
  skip:
    - win
    - osx and x86_64
  number: 0
  dynamic_linking:
    binary_relocation: false

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
  host:
    - nodejs 22.*
  run:
    - nodejs 22.*

tests:
  - script:
      - code-server --help
      - $CONDA_PREFIX/share/code-server/lib/vscode/node_modules/@vscode/ripgrep/bin/rg --version

about:
  license: MIT
  license_file:
    - code-server/LICENSE
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.
  homepage: https://coder.com
  repository: https://github.com/cdr/code-server
  documentation: https://coder.com/docs/code-server

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
