schema_version: 1

context:
  name: code-server
  version: "4.105.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://github.com/coder/code-server/releases/download/v${{ version }}/code-server-${{ version }}-linux-amd64.tar.gz
      sha256: e2843456df7e1b0a7ee03315b572a2c4317237f14529ab2f7dda8d85309f08f0
      target_directory: code-server
  - if: linux and aarch64
    then:
      url: https://github.com/coder/code-server/releases/download/v${{ version }}/code-server-${{ version }}-linux-arm64.tar.gz
      sha256: 506e3ca055702035c268f89d969f7f4180f8dc2a34d376b83f725016fc441791
      target_directory: code-server
  - if: osx and arm64
    then:
      url: https://github.com/coder/code-server/releases/download/v${{ version }}/code-server-${{ version }}-macos-arm64.tar.gz
      sha256: 2ab02a543adc253cfab8341dae9808a58ac94ef54f7093dd8c13eb2d2a1a66b6
      target_directory: code-server

build:
  skip:
    - win
    - osx and x86_64
  number: 0
  dynamic_linking:
    binary_relocation: false

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
  host:
    - nodejs 22.*
  run:
    - nodejs 22.*

tests:
  - script:
      - code-server --help
      - $CONDA_PREFIX/share/code-server/lib/vscode/node_modules/@vscode/ripgrep/bin/rg --version

about:
  license: MIT
  license_file:
    - code-server/LICENSE
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.
  homepage: https://coder.com
  repository: https://github.com/cdr/code-server
  documentation: https://coder.com/docs/code-server

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
