schema_version: 1

context:
  name: code-server
  version: "4.109.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://github.com/coder/code-server/releases/download/v${{ version }}/code-server-${{ version }}-linux-amd64.tar.gz
      sha256: 3e54f91b4f7e2ccf2fe14e30fdcef88317c83ddbe06d1af2a5b8532996ffbe1e
      target_directory: code-server
  - if: linux and aarch64
    then:
      url: https://github.com/coder/code-server/releases/download/v${{ version }}/code-server-${{ version }}-linux-arm64.tar.gz
      sha256: 271ac6ec24c7283957fdc958fe196c5174e17ea67139977bade4ca8f31c50f0c
      target_directory: code-server
  - if: osx and arm64
    then:
      url: https://github.com/coder/code-server/releases/download/v${{ version }}/code-server-${{ version }}-macos-arm64.tar.gz
      sha256: a3e941c2cb7045ebef92073ee379726b8a235f8ee144f1988aff199b684c9e09
      target_directory: code-server

build:
  skip:
    - win
    - osx and x86_64
  number: 0
  dynamic_linking:
    binary_relocation: false

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
  host:
    - nodejs 22.*
  run:
    - nodejs 22.*

tests:
  - script:
      - code-server --help
      - $CONDA_PREFIX/share/code-server/lib/vscode/node_modules/@vscode/ripgrep/bin/rg --version

about:
  license: MIT
  license_file:
    - code-server/LICENSE
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.
  homepage: https://coder.com
  repository: https://github.com/cdr/code-server
  documentation: https://coder.com/docs/code-server

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
