bot:
  automerge: true
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
os_version:
  linux_64: cos7
github:
  branch_name: main
  tooling_branch_name: main
test: native
conda_build:
  pkg_format: '2'
